activation_mode: 0
activation_pages: 'admin\nadmin/*'
add_css_media: 'all'
add_css_preprocess: true
add_js_defer: false
add_js_preprocess: true
add_js_scope: 'header'
auto: true
auto_custom_markup: ''
auto_disabled_class: 'no-code'
auto_element_class: '.content'
auto_markup:
  code: 'code'
  pre: 'pre'
  precode: 'precode'
behaviour_extensions: ''
behaviour_linenums: 0
css: 'default'
css_path: ''
